<a href="https://colab.research.google.com/github/vchai03/Math-Modelling/blob/main/FipsCodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd, numpy as np

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
df=pd.read_csv("/content/drive/My Drive/Modeling/countyTot.csv")
DF=pd.read_csv("/content/drive/My Drive/Modeling/FIPSCodes.csv")

#function: retrieves county name based on fips code
#return DF[DF.FIPS == fip].Name
def get_county_name(fip):
  if (DF.loc[DF.FIPS == fip, 'Name'].values.size == 0):
    return 'error'
  else:
    return DF.loc[DF.FIPS == fip, 'Name'].values[0]

#DF.loc[DF.FIPS == 1003, 'Name'].values[0]
#df.assign(county = df['fip'].apply(lambda x: get_county_name))
df['county'] = df['fip'].apply(get_county_name)
df.loc[df.county == 'error']
#df.head()

        Unnamed: 0  year  month    fip    prp  ...   min   max  CDD   HDD  county
372            372  1989      1  11003   4.25  ...  30.2  50.5    0   764   error
373            373  1989      2  11003  10.24  ...  23.4  39.3    0   943   error
374            374  1989      3  11003   6.10  ...  36.7  56.9    8   572   error
375            375  1989      4  11003   2.69  ...  44.8  69.3   13   251   error
376            376  1989      5  11003   2.09  ...  52.2  76.0   83   111   error
...            ...   ...    ...    ...    ...  ...   ...   ...  ...   ...     ...
368275      368275  2019      8  47078   3.14  ...  52.6  75.3   64    98   error
368276      368276  2019      9  47078   7.05  ...  51.6  69.4   21   156   error
368277      368277  2019     10  47078   4.83  ...  35.8  54.0    0   622   error
368278      368278  2019     11  47078   1.67  ...  22.6  34.9    0  1088   error
368279      368279  2019     12  47078   3.58  ...  15.9  29.5    0  1310   error

[165912 rows x 11 columns]